### ISSUE TITLE
Make available on Confluent Hub?

### ISSUE THREAD

**Issue by rmoff** [an0r0c/kafka-connect-transform-tojsonstring#1]
Hi, this looks like a great plugin! Would you consider making it available on Confluent Hub? This way many more people can find it and use it with a command line installation. 
[There's details here](https://docs.confluent.io/home/connect/confluent-hub/contributing.html) on submitting to Confluent Hub.

**Comment by an0r0c** [comment]
Hi @rmoff, basically I plan to make it available on Confluent Hub but didn't had time to dig into the necessary steps. Hopefully I'll find the time in the next few weeks.

**Comment by rmoff** [comment]
Sounds great! Let me know if you get stuck and I can help.

**Comment by SanjayKantheti** [comment]
@an0r0c Is it now available in confluent hub ?

**Comment by an0r0c** [comment]
Finally it's listed :) https://www.confluent.io/hub/an0r0c/kafka-connect-transform-record2jsonstring
