### ISSUE TITLE
Post Process JSON to XML: is resulting XML string "pretty" or "minified"?

### ISSUE THREAD

**Issue by pf7273** [an0r0c/kafka-connect-transform-tojsonstring#2]
Hello,
I am new here, so I have a question: if post.processing.to.xml is set to true,	is resulting XML string "pretty" or "minified"?

Thanks,
Petr

**Comment by an0r0c** [comment]
I checked the unit tests for it (https://github.com/an0r0c/kafka-connect-transform-tojsonstring/blob/3523ac4466aa799e5ecb5b3513694fe16213ea53/src/test/java/com/github/cedelsb/kafka/connect/smt/Record2JsonStringConverterTest.java#L250) there it looks "minified" so without line breaks and spaced.

**Comment by pf7273** [comment]
Thank you.

**Comment by an0r0c** [comment]
A quick google search brought me to https://stackoverflow.com/questions/139076/how-to-pretty-print-xml-from-java  - it seems "beatified" printing should be possible with small enhancements. 

But for now I don't see the need for it but feel free to provide a PR if you see value in it.
